spring:
  application:
    name: whatsapp-flow-challenge

  datasource:
    url: jdbc:postgresql://localhost:5432/whatsapp_flow
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

  flyway:
    enabled: true

server:
  port: 8080