spring:
  application:
    name: whatsapp-flow-challenge

  datasource:
    url: jdbc:postgresql://localhost:5432/whatsapp_flow
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false

  flyway:
    enabled: true

server:
  port: 8080
wppconnect:
  url: http://localhost:21465
  token: seu-token
  session: minha-sessao
